# Generated by Django 5.1.7 on 2026-05-11 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.CharField(max_length=100)),
                ('loc', models.TextField()),
                ('inv', models.CharField(max_length=30)),
                ('occ', models.CharField(max_length=200)),
                ('dmg_raw', models.BigIntegerField(default=0)),
                ('alarm', models.CharField(max_length=20)),
                ('sta', models.CharField(max_length=100)),
                ('eng', models.CharField(max_length=100)),
                ('by_user', models.CharField(max_length=200)),
                ('inj_c', models.IntegerField(default=0)),
                ('inj_b', models.IntegerField(default=0)),
                ('cas_c', models.IntegerField(default=0)),
                ('cas_b', models.IntegerField(default=0)),
                ('rem', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
